### ISSUE TITLE
core.js -VS- global pub/sub

### ISSUE THREAD

**Issue by markmarijnissen** [mauriciosoares/core.js#25]
I'm trying to understand core.js.

* Every module has an `init` and `destroy`
* Every module can `listen` and `notify` (i.e. a global pub/sub)
* A module can be coupled to a DOM element.

Correct?

I could implement the same with a global pub/sub system and a single Mediator:

* Let every module emit a `created(name)` event when it is defined.
* The Mediator listens to `created` events and keeps a list of module names.
* `Mediator.start(xxxx)`: emits `started xxxx(DOMElement)` where `xxxx` is the module name. 
* `Mediator.stop(xxxx)`: emits `stopped xxxx` where `xxxx` is the module name.

Should be the same functionality, only a different way to view it... right?

**Comment by mauriciosoares** [comment]
Hello @markmarijnissen , thanks for getting interested on Core.js

To your first question:
Yes, basically that's how core.js works

And to the second question:
I may say yes, they would work basically the same, but the idea of Core.js is that the Core component has access to extensions (aka jQuery), and that the modules should never talk to other extensions or other modules directly, for that you use the `sandbox`.

Also not everybody knows how to create a cool structure using pub/sub and a mediator, Core.js helps with that as well since those features are already built-in, you just have to code :)

I get what was your point, and if you know how to structure your files, and know how to implement a cool mediator + pub/sub, then you probably don't need Core.js

Otherwise it would help you a lot, principally to understand how to structure your app if you don't have much experience with Javascript.

What do you think?

**Comment by markmarijnissen** [comment]
Yes, I agree. It helps to have libraries that support in having a proper structure.

I am curious - do you have any experience building (big or small) apps using core.js?

As my own software development experience gains, I try to develop a "design philosophy" that helps me make good apps. I've noticed pro's and cons from all kinds of approaches (i.e. SpineJS, Backbone, AngularJS, plain old javascript, etc).

Currenty I'm a fan of a [mediator-ish structure](https://github.com/markmarijnissen/js-mediator) - where I have absolutely **no** requirements of the the code I am using. I could use any EventEmitter, Router, jQuery, etc. In my opinion, it is a huge advantage that you don't have to wrap your code in any framework code.

Then - the big benefit I discovered: A design philosophy should have room for "messy" code. It often takes me a few (2-3) iterations before I fully grasp the scope of the problem and I can write code. With my current "Mediator" philosophy, I independent, standalone modules that do one thing, and one thing well. The Mediators couple everything together. It's easy for me to throw away or replace Modules that are not working. For more complicated stuff, I can also write a big, ugly, coupled Mediator... and once I have fully implemented everything, I can refactor it into independent modules. (Which I often like to share on NPM/Bower).

The Core.js library does many things I realy enjoy. In particular, it facilitates a clean seperation of concern. There is a place for independent, standalone modules.... and there is a place for coupling everything together.

Still - how would you combine Core.js with a library like Famo.us? Or with Backbone? I am curious!

**Comment by mauriciosoares** [comment]
Cool, in fact the mediator pattern helps with a lot of stuff, and can be a standalone approach to develop small size and big size applications.

Unfortunately since core.js is too young, and I'm not working very often on personal projects (other then Core.js) I have not implemented it in any app... Also I don't know the "best" approach to combine a third party framework (like backbone) using Core.js, but I'd to something like that:

```js
Core.extend('Backbone', {}); // $1

Core.register('tweet-list', function(sandbox) {
  function setListView() { // $2
    return sandbox.x('Backbone').View.extend({
      el: this.el // $3
    });
  }

  return {
    init: function() {
      this.View = setListView.apply(this); // $4

      // code, code, code
    }
  }
});

Core.start('tweet-list');
```

$1 First of all I extend Core's features using the extend method

$2 Inside the module, i created a simple function just to config the View using backbone

$3 Since the module name is a reference for an element in the DOM, I can reference it to the `el` of 
the View configuration (isolation of the DOM)

$4 After init is triggered, I get a reference into `this.View` of the Constructor created by backbone, so I can use it in other methods.

Note: I use `apply` to call the setListView, since the `this.el` inside the `setListView` method would not be accessible.


After that is up to your imagination to continue coding. 

Again, don't know if this would be the best approach, but if I would start from scratch, that would be something acceptable in my opinion. What do you think about this code? do you have a better idea of how to structure it?

**Comment by mauriciosoares** [comment]
@markmarijnissen any thoughts on what I said?

:)

**Comment by markmarijnissen** [comment]
Hey - yes I have some thoughts about it.

I don't see the added benefit of the "extensions". Your module is still tightly coupled to BackBone.

1. If `sandbox.x('BackBone')` does not exist, what are you going to do? Re-implement the entire BackBone API?
2. It's just too easy to get a reference to some external library/object - this makes it easy to abuse; i.e. people ignoring strict module seperating by adding "extentions"

I think key to proper encapsulated modules is to meet following conditions:
* coupling should be kept to a minimum (i.e. only use BackBone View, not entire BackBone lib)
* coupling should be in language of the module - i.e. it shouldn't be `x(BackBoneView)` but just `x(CreateView)`. The implementation of CreateView is up to the developer.

This way, the interface of modules to other modules is three-fold
* notify (emit events)
* listen to events
* call global functions

In a way, "global functions" are not even really needed. You could always do:
```javascript
notify('createView',function callback(view) { // .... });
```

Although working with callbacks for calling synchronous methods might be cumbersome.

**Comment by mauriciosoares** [comment]
I see, so instead of extending the entire Backbone library, I'd extend only what I need from backbone (views for example)?

And even further, I could extend Core with a method created by my own that just returns an instance of a Backbone View? That looks like a better approach then the one I've showed you.

Just one question, I don't quite get the `notify('createView', function() {});`, did you really meant `notify`?

**Comment by jaetask** [comment]
Interesting. I like the direction of this. Its better to have a simple well defined API structure to Core.js and have 'plugins' or 'helpers' that implement connecting that API to Backbone, React or whatever.

This needs to be thought about properly, and from a higher level. 

I also agree with mark, `sandbox.x('BackBone')` should not be available, but I do not like the idea of global functions. Any interaction between modules must come via messages and messages only. Senders must not know anything about receivers or even if anything reacted to them. If a Sender must get info from outside, then it should be done view a Receiver message. 

The thing is, at some point you are going to need to write some Backbone code. No matter how well its abstracted, this is what will do the work. So where would this go?

**Comment by jaetask** [comment]
I've been thinking about this and following on from @allain pull request https://github.com/mauriciosoares/core.js/pull/30 I think we have come across something really important.

If we extend core.Start to accept an array of modules then we could effectively produce the kind of split thats required for loading above the fold items.

```
Core.start(['above-the-fold-a', above-the-fold-b']).then(function(result) {
  console.log('Above the fold modules loaded', result);
  Core.start('less-important-module');
});
```

What do you think?

**Comment by allain** [comment]
I like it. Though if you are doing that it's tempting to overload start so
that no arguments means "all" and then deprecate startAll

**Comment by mauriciosoares** [comment]
Yeah, science bitch! (breaking bad quote),

I like your solution @jaetask, and we could indeed deprecate `startAll` like @allain said.

I'll definitely work on this.

**Comment by mauriciosoares** [comment]
I'll close this issue by now... since we changed our subjects here... and i've opened a new issue #32, if you guys are interested on suggesting some other things
