### ISSUE TITLE
Support Asynchronous Construction

### ISSUE THREAD

**Issue by allain** [mauriciosoares/core.js#26]
Theoretically, starting a module might require calling some asynchronous APIs (IndexDB for example).

Until those asynchronous API calls are complete, the module may not be ready to handle incoming notifications. One solution is to code the module to buffer them internally until the module decides for itself that it is ready to process them. This would not be great.

To resolve this, the framework could be extended to emit module state changes: starting, started.

Then, the init code could be extended to accept an optional callback, or to allow returning a promise.

If neither of those approaches are used, the `starting` notification is emitted, before init is called, and `started` after it has completed.

Otherwise started is emitted on callback invocation, or when the returned promise resolves.

Given this change, `start` and `startAll` could be extended to accept callbacks, or return promises themselves allowing things like:

```js
.startAll(function(err) {
  // do stuff
});
```
or
```js
.startAll().then(function() {  
  // broadcast 'ready' event
});
```

This applies to the init method but would likely have its equivalents for other methods too.

Does this interest anyone?

**Comment by mauriciosoares** [comment]
Cool, that's a nice idea, and I'll try to expend the next days working on that.

Just to share my thoughts about how it would work, what do you think of this:

```js
Core.register('module:async', function() {
  return {
    init: function() {
      ajaxCall(function() {
        this.resolve();
      }.bind(this));
    }
  };
});

Core.start('module').then(function() {
  // After this.resolve gets called
  Core.start('othermodule');
});

// same thing with startAll
Core.startAll().then(function() {
  
});
```

If you want this module to be async, then you set the name of the module with :async, if this is passed then the module will automatically have an `resolve` method to be triggered whenever you want it to be triggered. And I'd handle the module like a promise as you said.

Just one thing, since the `this.resolve` would probably be called in an callback function, you would have to manually set the value of `this` on this callback using `bind` or `$.proxy` for example, do you think on a different approach for that?

What do you think of the general idea of implementation?

**Comment by mauriciosoares** [comment]
Ah, since my friend @jaetask talked about this same feature in a previous issue (#14), I'd love to include him on this discussion to hear his thoughts about this.

**Comment by allain** [comment]
I had not considered that particular way of doing asynchrony. How would you
handle making teardown of a module?

So that you could handle:

Core.stop('blah').then(...)

**Comment by mauriciosoares** [comment]
Well, I guess you could use the `resolve` method as well, since all modules have a `destroy` method that is triggered when a module is stopped, you could do like this:

```js
Core.register('module:async', function() {
  return {
    destroy: function() {
      ajaxCall(function() {
        this.resolve();
      }.bind(this));
    }
  };
});

Core.stop('module').then(function() { /* asweome code */});
```

Using the `:async` in the modules name gives you the ability to use `resolve` in both initializing and destroying a module, but you don't have to use it if you don't want to, since the `resolve` method is used only as a callback to the `Core`'s calls, so you could use `resolve` in a `init` method and not in a `destroy` method and vice versa.

How were you thinking of handling the asynchrony in modules?

**Comment by allain** [comment]
I see. Conceivably the destroy method may not need to be synchronous and the init method could be asynchronous.

I'd thought that returning a promise from the init or destroy methods would be the easiest approach.

In all cases synchronous or not `Core.start('module').then(function() { ... });` would be doable.

pseudocode within Core.start:

```js
// emit starting
var result = constructor.init();
Promise.resolve(result).then(function() {
    //emit started
   return Promise.resolve();
});
```

Even in the case of no return value from `init` it would support the approach.

**Comment by mauriciosoares** [comment]
Got it, I think I had an even bigger idea,

I could implement promises in the jquery style (using deferred) into the core of sandbox, and then I can use wherever I want into my module...

And always return in the `start` and `stop` method the value returned from  `init` and `destroy` from the module, this way I can get the promise, and use it the way you said. So the implementation would be something like this:

```js
Core.register('module', function(sandbox) {
  return {
    init: function() {
      this.deferred = new sandbox.Deferred()

      ajaxCall(callback.bind(this));

      return deferred.promise();
    },

    callback: function() {
      this.deferred.resolve();
    }
  }
});

Core.start('module').then(function() { /* code */ });
```

It solves your problem of ajax calls in the start and stop of the module, also gives you the power to use promises wherever you want.

What about that?

**Comment by mauriciosoares** [comment]
Anyway,  your idea is really cool, and i'll definetly implement it into core.js

That will probably help to deal with a lot of things relates to async calls.

**Comment by allain** [comment]
I'm not sure there is anything gained by using deferred like this.

It adds stuff to the core and forces the module writers to call resolve on
it.

Core.register('module', function(sandbox) {
  return {
    init: function() {
      return Http.get(url).then(function(body) {

        //setup module

                return true;

      });
    },
  }
});

Core.start('module').then(function() { /* code */ });

**Comment by mauriciosoares** [comment]
Well, I think the gain is to be able to use promises anywhere in my modules.

And I know that `Http` is just a sample, but are you suggesting that it is an implementation of a ajax object inside Core? Because I did't quite get what you mean by that.

Otherwise, if you are suggesting that it is just a common library (like jQuery), than a way to handle async would be by returning whatever I want in the init method... then I'd return just an jQuery ajax promise, and handle in the `start` method, just like you said:

```js
Core.extend('$', jQuery);
Core.register('module', function(sandbox) {
  return {
    init: function() {
      return sandbox.x('$').ajax({ url: 'list.json' });
    }
  }
});

// here i get the promise from jquery
Core.start('module').then(function() {});
```

This way makes things waaaaaaay simpler to implement, and accomplish what you were saying.

Also gives you the ability to return other stuff from a module when you are starting or destroying it.

Sorry for extending this issue so much, but it's cool to discuss this kind of stuff.

**Comment by allain** [comment]
No apologizing needed.

My point was just the the init (or any other method) could make use of any
3rd party library that returns a promise and then work with it as it sees
fit using tools already available for working with promises. No need to
complicate things for something that promises already solve.

I'd expect that the thenable returned from start wouldn't resolve to a
value, since that value would only be needed inside the init.

**Comment by mauriciosoares** [comment]
I see, indeed there's no need to the ajax result become available in the start returned promise...

I guess at first I'll implement it this way, since its a good to have feature, and this way it will become available quicker... But after that I'll see what I can do not to return a unneeded value in the start's promise.

Do you think that's acceptable for now?

**Comment by allain** [comment]
Sure do.

**Comment by mauriciosoares** [comment]
Cool, I'll close this issue by now, and open a new one specifying the feature, 

Thanks for all the help @allain

**Comment by jaetask** [comment]
Hi Guys, sorry for the delay, Github still points to an old email address, I will change this now.

So, Ive just read the thread, I really like the idea. We are going to need separation and notifications of when things have happened. Also very important it is not jQuery specific, I am personally heading more towards Zepto, day by day.

**Comment by mauriciosoares** [comment]
:)

**Comment by allain** [comment]
Any luck implementing this @mauriciosoares ? Want me to take a stab at it?

**Comment by mauriciosoares** [comment]
As we discussed, at first I'd implement the `Start` and `Stop` method to return whatever the `init`  and `destroy` method would return, since we could return a promise from an external lib (jQuery or Zepto for example).

And that's already implemented. Available in the version 0.3.0

Take a look if is that what you expected :)

**Comment by allain** [comment]
Hey, looks good, I suppose the next step is to support it not considering the module started until the promise resolves and then having startAll() resolve only when all of the start promises resolve from the individual promises.

**Comment by mauriciosoares** [comment]
"support it not considering the module started until the promise resolves" I didnt get what you mean by that... Probably because of my poor english :)

You mind explain it in more details?

**Comment by allain** [comment]
It was my grammar.

Until a returned promise resolves, that init call cannot be considered
complete.

When calls to Core.startAll().then(function() {...}) are made, the then it
should not invoke `then` until all of the modules have resolved.

If it's unclear what I mean, I can create a PR for it.

**Comment by mauriciosoares** [comment]
Oh, i see. the startAll part was very clear, and I find it very useful indeed.

So you think I should create a "beforeInit" method, which will be used when starting a module? for example:

```js
Core.start('module').before(function() {
  // This gets called before the init method
}).after(function() {
  // this gets called when the promise returned from the init method gets resolved
});
```
