### ISSUE TITLE
sandbox.x looks like a bit weird

### ISSUE THREAD

**Issue by hwclass** [mauriciosoares/core.js#34]
Just a thought, can it be nice to override the current "sandbox.x" method to something meaninful? The dependencies as libraries and other code pieces are loaded into context by this method. For example,  "get" or "load" can be great. If there is any thought t do it, I can.

**Comment by hwclass** [comment]
This could also be "use" maybe..

**Comment by mauriciosoares** [comment]
I choose `x` because it kinda remember "extension" (at least to me kkk).

I don't think `load` would be a good name, since it's not loading the lib, and `get` seems a bit strange to too.

But indeed `use` would be a good name. I'll keep it as `x` for now, and as soon as I finish working o the other issues, I'll check which would be a good name to use instead of `x`.

I'll not be able to work on any issue this week, since I'm participating on a hackathon, but as soon as it ends, I'll be back to work on Core.js

Thanks for opening the issue.

**Comment by hwclass** [comment]
After your post, "use" sounds better to me. If it is not a seperate module to load for functionality, it could be get or load but "use" is the best, I think. Thanks. IF you do not have time, I can work on it in a branch.

**Comment by mauriciosoares** [comment]
Hey @hwclass, sorry for taking so long to work on this issue... I was working on a project for a hackathon, and since it's over now I can go back to work in Core.js

I've just merged a branch which I changed `x` to `use` in the sandbox :) I'll close this issue

Thanks for the tip.
