### ISSUE TITLE
Change grunt to gulp

### ISSUE THREAD

**Issue by mauriciosoares** [mauriciosoares/core.js#44]
Well, I don't have much expertise in gulp, that would be a nice thing :)

**Comment by GrosSacASac** [comment]
What are the motivations for the switch ?

**Comment by hwclass** [comment]
Hey @mauriciosoares & @GrosSacASac, since it is a pure JS lib, maybe need to consider [Rollup](https://github.com/rollup/rollup) or something like that which fits better for a library development/automation for different apporaches (commonjs, umd, esm, etc.).

**Comment by GrosSacASac** [comment]
Hi @hwclass We will use rollup as bundler for sure. Grunt and Gulp are not bundlers, they are tasks runners, so we can use rollup inside grunt if you see what I mean. Task runner can define task like linting, testing etc. Nowadays the most popular task runner is webpack, which also contains a bundler (webpack bundler). Webpack is made for apps, not libraries so there is no benefit of using it.

I asked a few friends, and it turns out grunt and gulp are almost the same, grunt is very similar to npm scripts, and gulp uses an asset pipelining paradigm.

**Comment by mauriciosoares** [comment]
There were actually no specific motivation for changing from grunt to gulp 😅, I don't think that's necessary at all, and I like the idea of using rollup instead of any task runner, and use npm scripts to run the commands, to make it more lightweight.
